### ISSUE TITLE
Can't compile simple script using default dependencies

### ISSUE THREAD

**Issue by Bios-Marcel** [samp-dev/fiddle#3]
The dependency `a_samp` can't be found and it can't be added manually.

![bug](https://user-images.githubusercontent.com/19377618/55295775-69efa100-5411-11e9-9885-88f550147d4e.png)

**Comment by spacemud** [comment]
This is provided by `sampctl/samp-stdlib`. It should probably be included by default.

**Comment by Bios-Marcel** [comment]
wth, did Github/peek delete my comment? :angry: I had already mentioned multiple solutions!
