### ISSUE TITLE
Captchas are being spammed

### ISSUE THREAD

**Issue by Bios-Marcel** [samp-dev/fiddle#4]
Every single time I run, I get a captcha, even though I am not doing anything out of the ordinary. And so far I have correctly succeeded every captcha on first try.

**Comment by Bios-Marcel** [comment]
Seemingly this is due to the dependency `samp-stdlib` missing.

There are multiple way to fix this:

* Guide the user through creating their fiddle
* Remove the default dependency
* make it findable by typing `a_samp`
* Just add the dependency by default

**Comment by pkfln** [comment]
This is not a project specific issue. I just lowered the security level of the reCAPTCHAs on sa-mp.dev (temporarily).
